#!/bin/sh -u
exec 2>&1
. /etc/runit/functions
. /etc/rc.conf

msg "waiting on init..."
while [ ! -f /var/tmp/.first_init ]; do sleep 3; done

# should the agent run?
if ! $( rc_get_agent_enable ); then
    msg_ok 'agent is disabled'
    sv stop miyagi
fi

USER_CONFIG_FILE=/etc/miyagi/configuration_user.json

# default values for http server
_gui_www="\"/www\""
_gui_port=443
_gui_file_watch=false

# determine GUI toggle
if $( jq .extension_openros.gui_file_watch ${USER_CONFIG_FILE} ); then
    _gui_file_watch=true
    # GUI toggle enabled
    _gui_enabled=$( cat /mnt/flash/GUI_enabled )
    _gui_mode=$( cat /mnt/flash/GUI_mode )

    if [[ "${_gui_enabled}" == "true" ]] ; then
        if [[ "${_gui_mode}" == "http" ]] ; then
            _gui_port=80
            _cert=null
            _key=null
            jq 'del(.connection_websocket)' ${USER_CONFIG_FILE} > temp.json && cat temp.json > ${USER_CONFIG_FILE} && rm temp.json
            sleep 0.5
            jq '. + {"connection_websocket": {"default": {"port": 80, "www": "/www", "cert": null, "key": null}}}' ${USER_CONFIG_FILE} > temp.json && cat temp.json > ${USER_CONFIG_FILE} && rm temp.json            sleep 0.5
            sleep 0.5
        else
            if [[ "${_gui_mode}" == "https" ]] ; then
                _gui_port=443
                jq 'del(.connection_websocket)' ${USER_CONFIG_FILE} > temp.json && cat temp.json > ${USER_CONFIG_FILE} && rm temp.json
                sleep 0.5
                CERT=$(rc_get_agent_http_cert)
                KEY=$(rc_get_agent_http_key)
                jq --arg cert "$CERT" --arg key "$KEY" '. + {"connection_websocket": {"default": {"port": 443, "www": "/www", "cert": $cert, "key": $key}}}' ${USER_CONFIG_FILE} > temp.json && cat temp.json > ${USER_CONFIG_FILE} && rm temp.json
                sleep 0.5
            fi
        fi
    else
        if [[ "${_gui_enabled}" == "false" ]] ; then
            _gui_port=80
            _gui_www=null
            _cert=null
            _key=null
            jq 'del(.connection_websocket)' ${USER_CONFIG_FILE} > temp.json && cat temp.json > ${USER_CONFIG_FILE} && rm temp.json
            sleep 0.5
            jq '. + {"connection_websocket": {"default": {"port": 80, "www": null, "cert":null, "key": null}}}' ${USER_CONFIG_FILE} > temp.json && cat temp.json > ${USER_CONFIG_FILE} && rm temp.json
            sleep 0.5
        fi
    fi
fi



# determine agent log level
_configLogLevel=$( rc_get_agent_log_level )
_agentLogLevel=""
case "${_configLogLevel}" in
    0) _agentLogLevel=" ";;
    1) _agentLogLevel="-v1";;
    2) _agentLogLevel="-v2";;
    *) _agentLogLevel=" ";;
esac

sleep 1.5

msg "executing miyagi binary..."
exec miyagi ${_agentLogLevel}
